development:
  adapter: mysql2
  encoding: utf8
  database: cni
  pool: 5
  username: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  database: cni_test
  username: root

production:
  adapter: mysql2
  encoding: utf8
  database: cni
  pool: 5
  username: root
  password: <%= ENV['MATRIX_DB_PASSWORD'] %>
  host: localhost
